config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  get "about", to: "articles#about"
  resources :articles, except: [ :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :author, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    set_article
  end

  def destroy
    article = Article.find(params[:id])
    if article.destroy
      flash[:success] = 'The article was successfully deleted'
      redirect_to root_path
    else
      flash.now[:danger] = 'There was a problem deleting the article :('
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'The article was successfully uploaded'
      redirect_to @article
    else
      flash.now[:danger] = 'There was a problem uploading the article :('
      render new_article_path
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/about.html.erb
<h1>whoami</h1>
<br />
<p>My name is Kai Takami and I am a highly motivated and detail-oriented individual with a strong passion for startups.

I am skilled in React.js, Next.js, Ruby on Rails and Python and have a proven track record of success in competitive programming platforms like codeforces or atcoder. I am a team player and thrive in collaborative environments, but am also comfortable working independently and taking on leadership roles.

Outside of work, I enjoy cycling and am always looking for new opportunities to learn and grow both personally and professionally. I am excited to bring my skills and enthusiasm to any organization and make a positive impact.</p>

app/views/articles/index.html.erb
<h1>Welcome to my personal website! 🙋</h1>
<h3>I'm Takami Kai</h3>
<p>Highly motivated and detail-oriented individual with a strong passion for startups.</p>
<br />
<section>
    <h2>My articles:</h2>
    <% @articles.each do |article| %>
        <div class="article-container">
            <h3><%= article.title %></h3>
            <div class="article-details">
                <p>Author: <%= article.author %></p>
                <p>Date: <%= article.created_at %></p>
            </div>
            <%= button_to "Show article", article_url(article), method: :get %>
        </div>
    <% end %>
</section>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<div class="form">
    <%= form_with model: @article do |form| %>
    <div class="input-container">
        <%= form.label :title, "Title" %>
        <%= form.text_field :title %>
    </div>
    <br />
    <div class="input-container">
        <%= form.label :description, "Body" %>
        <%= form.text_area :description %>
    </div>
    <br />
    <div class="input-container">
        <%= form.label :author, "Author" %>
        <%= form.text_field :author %>
    </div>
    <%= form.submit 'Upload' %>
    <% end %>
</div>

app/views/articles/show.html.erb
<br />
<h1><%= @article.title %></h1>
<div class="article-details">
    <p>Author: <%= @article.author %></p>
    <p>Date: <%= @article.created_at %></p>
</div>
<br />
<p><%= @article.description %></p>
<%= button_to "Delete Article", article_url(@article), method: :delete, class: "delete-button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="nav">
    <ul class="nav-list">
      <li class="nav-el nav-title"><%= link_to "Articles", root_path %></li>
      <li class="nav-el"><%= button_to "New Article", new_article_path, method: :get %></li>
    </ul>
  </nav>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:success] %>
    <div class="success"><%= flash[:success] %></div>
  <% end %>
  <% if flash[:danger] %>
    <div class="danger"><%= flash[:danger] %></div>
  <% end %>
    <%= yield %>
  </body>
</html>